# Generated by Django 5.2.7 on 2025-10-09 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'JOURNALIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='articles_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalistprofile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'READER'}, related_name='journalists_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'EDITOR'}, related_name='publishers_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='subscribers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'READER'}, related_name='publishers_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
