# Generated by Django 5.2.7 on 2025-10-09 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('news_application', '0003_resettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publisher_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('READER', 'Reader'), ('JOURNALIST', 'Journalist'), ('EDITOR', 'Editor')], default='READER', max_length=20),
        ),
    ]
