# Generated by Django 5.2.7 on 2025-10-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_application', '0004_alter_article_publisher_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('CURRENT_EVENTS', 'Current Events'), ('SPORTS', 'Sports'), ('PERSONAL_FINANCE', 'Personal Finance'), ('LIFESTYLE', 'Lifestyle'), ('CRIME', 'Crime'), ('POLITICS', 'Politics'), ('ENTERTAINMENT', 'Entertainment')], default='CURRENT_EVENTS', max_length=25),
        ),
    ]
