# Generated by Django 5.2.7 on 2025-10-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_application', '0005_remove_article_url_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
