# Generated by Django 5.2.7 on 2025-10-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_application', '0006_alter_article_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
