# Generated by Django 5.2.7 on 2025-10-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_application', '0007_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('AWAITING APPROVAL', 'Awaiting Editor Approval'), ('REJECTED', 'Rejected by Editor')], default='DRAFT', max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('CURRENT_EVENTS', 'Current Events'), ('SPORTS', 'Sports'), ('PERSONAL_FINANCE', 'Personal Finance'), ('LIFESTYLE', 'Lifestyle'), ('CRIME', 'Crime'), ('POLITICS', 'Politics'), ('ENTERTAINMENT', 'Entertainment'), ('OPINION', 'Opinion'), ('TECHNOLOGY', 'Technology')], default='CURRENT_EVENTS', max_length=25),
        ),
    ]
