# Generated by Django 5.2.7 on 2025-10-10 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_application', '0008_article_publication_status_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'JOURNALIST'}, related_name='publishers_you_write_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'EDITOR'}, related_name='publishers_you_edit_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
