# Generated by Django 5.2.7 on 2025-10-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_application', '0009_publisher_journalists_alter_publisher_editors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
    ]
